Added 3 sorting techniques and 1 String program.
fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY pull request #5
Opened 2022-10-02 06:22 UTC by karanS08

2022-10-02 06:29 UTC, Souvik-Nayak commented
The sorting techniques can be done as user input which will show result for different inputs !

2022-10-02 06:33 UTC, fms12 commented
add a comments for a better understanding

2022-10-02 07:00 UTC, fms12 commented on Searching & sorting/bubble_sort.py
> +    for i in range(len(list)):
add comments for explanation and make separate folder for sorting then try to push

2022-10-02 07:04 UTC, fms12 requested changes

2022-10-02 07:04 UTC, fms12 commented on Searching & sorting/bubble_sort.py
> +    for i in range(len(list)):
add comments for explanation and make separate folder for sorting then try to push

2022-10-02 07:04 UTC, fms12 commented on Searching & sorting/insertion_sort.py
> +                arr[j+1] = arr[j]
add comments

2022-10-02 07:04 UTC, fms12 commented on Searching & sorting/selection_sort.py
> +            if arr[min_index] > arr[j]:
add comments

2022-10-02 07:04 UTC, fms12 commented on String/Shuffle_string.py
> +    random.shuffle(word)
add comments

2022-10-03 08:57 UTC, karanS08 commented
@fms12  Please check now for any error.

2022-10-03 08:57 UTC, karanS08 commented
@fms12 Check now .

2022-10-03 16:21 UTC, fms12 approved these changes

2022-10-03 16:24 UTC, merged